/**
 * Expresscart
 * Expresscart API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface CartItem { 
    id?: any | null;
    quantity?: any | null;
    createdAt?: any | null;
    updatedAt?: any | null;
    CartId?: any | null;
    ProductId?: any | null;
}

