/**
 * Expresscart
 * Expresscart API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface User {
    /**
     * The ID of the user.
     */
    id: any | null;
    /**
     * The name of the user.
     */
    name: any | null;
    /**
     * The email of the user.
     */
    email: any | null;
    /**
     * The date and time when the user was last updated.
     */
    updatedAt: any | null;
    /**
     * The date and time when the user was created.
     */
    createdAt: any | null;
}

